// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace arma;

// posterior_with_control
vec posterior_with_control(umat Outcome);
RcppExport SEXP _TrendUtilities_posterior_with_control(SEXP OutcomeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< umat >::type Outcome(OutcomeSEXP);
    rcpp_result_gen = Rcpp::wrap(posterior_with_control(Outcome));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TrendUtilities_posterior_with_control", (DL_FUNC) &_TrendUtilities_posterior_with_control, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_TrendUtilities(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
