# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate a two-arm trial using Efron's biased coin design 
#'
#' 
#'
#' @param outcome
#' A matrix with one potential outcome data for each arm. The first column is the enrolment time, the second a place holder for the arm the third and fourth potential outcome for the SOC and the experimental arm
NULL

#' 
#'
#' @param alpha and beta, this are design parameter
#' 
#' 
#'
#' @param ret_prob 
#' if =1 return the probability to be assigned to the experimental arm for each of the subject.
#'                   //' @return
#' The function returns a outcome matrix with the allocations. 
#'
#'
#'@details This function implement the Efron's biased coin design
#'
NULL

#' @export
NULL

posterior_with_control <- function(Outcome) {
    .Call(`_TrendUtilities_posterior_with_control`, Outcome)
}

adaptiveBiasedCoin <- function(potential, alpha = 0.0, beta = 1.0, ret_prob = 0L) {
    .Call(`_TrendUtilities_adaptiveBiasedCoin`, potential, alpha, beta, ret_prob)
}

bar2arms <- function(potential, c = 1.0, M = 1L, ret_prob = 0L) {
    .Call(`_TrendUtilities_bar2arms`, potential, c, M, ret_prob)
}

doublyAdaptiveBiasedCoin <- function(potential, gamma, M = 1L, ret_prob = 0L) {
    .Call(`_TrendUtilities_doublyAdaptiveBiasedCoin`, potential, gamma, M, ret_prob)
}

randomizedPlayTheWinner <- function(potential, beta = 1L, alpha = 1L, M = 1L, ret_prob = 0L) {
    .Call(`_TrendUtilities_randomizedPlayTheWinner`, potential, beta, alpha, M, ret_prob)
}

barBattle2arms <- function(potential, alpha = 1.0, beta = 1.0, M = 1L, minProb = 0.1, ret_prob = 0L) {
    .Call(`_TrendUtilities_barBattle2arms`, potential, alpha, beta, M, minProb, ret_prob)
}

